# Configuration file for the SQL database agent that provides:
# - Natural language to SQL query conversion
# - Query execution against multiple database types (MySQL, PostgreSQL, SQLite)
# - Results in multiple formats (YAML, JSON, CSV, Markdown)

---
log:
  stdout_log_level: INFO
  log_file_level: INFO
  log_file: logs/sam-sql-database.log

shared_config:
  - broker_config: &broker_connection
      dev_mode: ${SOLACE_DEV_MODE, false}
      broker_url: ${SOLACE_BROKER_URL}
      broker_username: ${SOLACE_BROKER_USERNAME}
      broker_password: ${SOLACE_BROKER_PASSWORD}
      broker_vpn: ${SOLACE_BROKER_VPN}
      request_reply_enabled: true

flows:
  # Flow to handle action requests
  - name: {{SNAKE_CASE_NAME}}_action_request_processor
    components:
      # Input from a Solace broker
      - component_name: broker_input
        component_module: broker_input
        component_config:
          <<: *broker_connection
          payload_encoding: utf-8
          payload_format: json
          broker_queue_name: ${SOLACE_AGENT_MESH_NAMESPACE}agent_{{SNAKE_CASE_NAME}}_action_request
          broker_subscriptions:
            - topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/actionRequest/*/*/{{SNAKE_CASE_NAME}}/>
              qos: 1

      # Custom component to process the action request
      - component_name: action_request_processor
        # path is completed at build time
        component_module: {{MODULE_DIRECTORY}}.agents.sql_database.sql_database_agent_component
        component_config:
          llm_service_topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/llm-service/request/general-good/
          embedding_service_topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/embedding-service/request/text/
          agent_name: {{SNAKE_CASE_NAME}}
          db_type: ${{{SNAKE_UPPER_CASE_NAME}}_DB_TYPE}
          host: ${{{SNAKE_UPPER_CASE_NAME}}_DB_HOST}
          port: ${{{SNAKE_UPPER_CASE_NAME}}_DB_PORT}
          user: ${{{SNAKE_UPPER_CASE_NAME}}_DB_USER}
          password: ${{{SNAKE_UPPER_CASE_NAME}}_DB_PASSWORD}
          database: ${{{SNAKE_UPPER_CASE_NAME}}_DB_NAME}
          query_timeout: ${{{SNAKE_UPPER_CASE_NAME}}_QUERY_TIMEOUT, 30}
          database_purpose: ${{{SNAKE_UPPER_CASE_NAME}}_DB_PURPOSE}
          data_description: ${{{SNAKE_UPPER_CASE_NAME}}_DB_DESCRIPTION}
          auto_detect_schema: true
        component_input:
          source_expression: input.payload

      # Output to a Solace broker
      - component_name: broker_output
        component_module: broker_output
        component_config:
          <<: *broker_connection
          payload_encoding: utf-8
          payload_format: json
          copy_user_properties: true
